server {
    listen 80;
    server_name ti.koljasam.com;

    if ($host = ti.koljasam.com) {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name ti.koljasam.com;

    ssl_certificate /etc/letsencrypt/live/ti.koljasam.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ti.koljasam.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location /static/ {
        alias /home/deploy/transparent-input/django-backend/staticfiles/;
    }

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
