# Generated by Django 6.0.6 on 2026-06-24 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('iso3', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('subtitle_language', models.CharField(max_length=10)),
                ('human_readable', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('topics', models.JSONField(blank=True, null=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='vocab.language')),
            ],
        ),
        migrations.CreateModel(
            name='VideoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline', models.CharField(max_length=50)),
                ('native_language', models.CharField(max_length=10)),
                ('segments', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='vocab.video')),
            ],
            options={
                'unique_together': {('video', 'pipeline', 'native_language')},
            },
        ),
    ]
