# Generated by Django 6.0.6 on 2026-06-18 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('iso3', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('subtitle_language', models.CharField(max_length=10)),
                ('human_readable', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=20, unique=True)),
                ('segments', models.JSONField()),
                ('topics', models.JSONField(blank=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='vocab.language')),
            ],
        ),
    ]
