# Generated by Django 6.0.6 on 2026-06-24 16:04

from django.db import migrations, models


def copy_subtitle_language(apps, schema_editor):
    Video = apps.get_model('vocab', 'Video')
    Language = apps.get_model('vocab', 'Language')
    lang_map = {lang.iso3: lang.subtitle_language for lang in Language.objects.all()}
    for video in Video.objects.exclude(language_id__isnull=True):
        bcp47 = lang_map.get(video.language_id)
        if bcp47:
            video.language_id = bcp47
            video.save(update_fields=['language_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(copy_subtitle_language, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='video',
            name='language',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
