# Generated by Django 6.0.6 on 2026-06-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_drop_language_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videotranslation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='videotranslation',
            name='checked_by_human',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videotranslation',
            name='level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('EXPERT', 'Expert')], default='INTERMEDIATE', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='videotranslation',
            unique_together={('video', 'pipeline', 'native_language', 'level')},
        ),
    ]
