# Generated by Django 6.0.6 on 2026-06-21 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0003_seed_vietnamese_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline', models.CharField(max_length=50)),
                ('target_language', models.CharField(max_length=10)),
                ('segments', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='vocab.video')),
            ],
            options={
                'unique_together': {('video', 'pipeline', 'target_language')},
            },
        ),
    ]
