# Generated by Django 6.0.6 on 2026-06-21 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0004_videotranslation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videotranslation',
            old_name='target_language',
            new_name='native_language',
        ),
        migrations.AlterUniqueTogether(
            name='videotranslation',
            unique_together={('video', 'pipeline', 'native_language')},
        ),
    ]
