# Generated by Django 6.0.6 on 2026-06-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0005_rename_target_language_videotranslation_native_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
